{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  ...
}: {
  # SEE ALSO: extra.nix
  home.packages = with pkgs; [
    adwaita-icon-theme
    adwaita-icon-theme-legacy
    alacritty
    any-nix-shell
    btop
    custom.archlinux-logout
    eza
    fastfetch
    feh
    font-awesome
    gnumake
    hyprland
    hyprshot
    imagemagick
    inputs.themecord.packages.x86_64-linux.default
    lutris
    lxappearance
    magic-wormhole
    mako
    mpv
    nemo-with-extensions
    nomacs
    p7zip
    pavucontrol
    pywal
    pywalfox-native
    rofi
    unstable.spicetify-cli
    swww
    telegram-desktop
    thunderbird
    udiskie
    hellwal
    vesktop
    waybar
    wget
    wl-clipboard
    wlroots
    wtype
    xorg.xrdb
  ];
}
